"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var isAuthenticated_1 = require("../middlewares/isAuthenticated");
var order_controller_1 = require("../controller/order.controller");
var router = express_1.default.Router();
router.route("/").get(isAuthenticated_1.isAuthenticated, order_controller_1.getOrders);
router.route("/checkout/create-checkout-session").post(isAuthenticated_1.isAuthenticated, order_controller_1.createCheckoutSession);
router.route("/webhook").post(express_1.default.raw({ type: 'application/json' }), order_controller_1.stripeWebhook);
exports.default = router;
